name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  policy_test:
    name: "Test Policies"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Run install
        run: yarn install --cwd policies --frozen-lockfile
      - name: Lint
        run: yarn --cwd policies run lint
        env:
          NODE_OPTIONS="--max_old_space_size=8192"
      - name: Test
        run: yarn --cwd policies run test
        env:
          NODE_OPTIONS="--max_old_space_size=8192"
      - name: Markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          globs: |
            README.md
